name: Update index.html

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v3

      - name: Instalacja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Uruchomienie skryptu
        run: python generate_index.py

      - name: Commit zmian
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Automatyczna aktualizacja index.html" || echo "Brak zmian do commitowania"
          git push
