name: Automatyczna aktualizacja index.html

on:
  push:
    branches: [ main ]  # lub inny branch, jeśli publikujesz inną gałąź

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ustaw Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Zainstaluj zależności (jeśli potrzebne)
        run: |
          pip install -r requirements.txt || true

      - name: Wygeneruj zaktualizowany index.html
        run: |
          python generate_index.py

      - name: Commit i push zmian
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Automatyczna aktualizacja index.html [bot]" || echo "Brak zmian do commitowania"
          git push
          
